### ISSUE TITLE
JDBC ClickHouseDriver does not denote a valid java.sql.Driver class name

### ISSUE THREAD

**Issue by changeling76** [mmsmdali/dremio-clickhouse-arp-connector#3]
I was able to build the connector, it's available in UI datasourece. However JDBC connection is not started. I copied clickhouse-jdbc-0.3.3-SNAPSHOT-all.jarjdbc jar to $DREMIO_HOME/jars/3rdparty folder. Also tried with different JDBC drivers changing  the config line 
private static final String DRIVER = "com.clickhouse.jdbc.ClickHouseDriver";  to what is described in driver manual.
The error message I get:

`... 
at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: String 'com.clickhouse.jdbc.ClickHouseDriver' does not denote a valid java.sql.Driver class name.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at com.dremio.exec.catalog.ManagedStoragePlugin.replacePlugin(ManagedStoragePlugin.java:1027)
	at com.dremio.exec.catalog.ManagedStoragePlugin.createOrUpdateSource(ManagedStoragePlugin.java:368)
	... 73 common frames omitted
Caused by: java.lang.IllegalArgumentException: String 'com.clickhouse.jdbc.ClickHouseDriver' does not denote a valid java.sql.Driver class name.
	at com.dremio.exec.store.jdbc.DataSources.newGenericConnectionPoolDataSource(DataSources.java:66)
	at com.dremio.exec.store.jdbc.conf.ClickHouseConf.newDataSource(ClickHouseConf.java:128)
	at com.dremio.exec.store.jdbc.JdbcSchemaFetcherImpl.start(JdbcSchemaFetcherImpl.java:293)
	at com.dremio.exec.store.jdbc.JdbcStoragePlugin.start(JdbcStoragePlugin.java:351)
	at com.dremio.exec.catalog.ManagedStoragePlugin.lambda$newStartSupplier$2(ManagedStoragePlugin.java:570)
	at com.dremio.exec.catalog.ManagedStoragePlugin.lambda$nameSupplier$4(ManagedStoragePlugin.java:638)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.clickhouse.jdbc.ClickHouseDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.dremio.exec.store.jdbc.DataSources.newGenericConnectionPoolDataSource(DataSources.java:62)
	... 9 common frames omitted
`

**Comment by changeling76** [comment]
finally found a problem. there was a space at the end of connection string. Misleading error message though...
